### PR TITLE
pull request for learning to model it myself

### PR DESCRIPTION
**Pull request by agamking**
Hi gabor csapo , im a learner in NLP modelling and wanted to train this project using English novels myself. hence the pull request for complete database

### CODE REVIEW

**Comment by campdav** [comment]
Hi @agamking , you asked to merge your modifications to the master branch, which using french novels. Is it what do you expect ?

**Comment by agamking** [comment]
No. Actually I just wanted to receive all the project files done over
English novel

**Comment by campdav** [comment]
Ok, no pb. So I close this request.
Have fun with the code :)

**Comment by agamking** [comment]
Also one thing, while running the code, the compiler was throwing an error saying “words_vocab.pkl not found”
Where do I find this file ? or how do I generate a custom one on my own ?
thanks for the quick replies
 

From: campdav
Sent: Tuesday, September 10, 2019 12:04 AM
To: campdav/Text-Generation-using-Bidirectional-LSTM-and-Doc2Vec-models
Cc: agamking; Mention
Subject: Re:[campdav/Text-Generation-using-Bidirectional-LSTM-and-Doc2Vec-models] pullrequest for learning to model it myself (#2)

Closed #2.

**Pull request closed without merging**
